#SPDX-License-Identifier: MIT-0
---
- name: Always pull the latest image
  community.docker.docker_image:
    name: abdelrraoufsaidi/tp-devops-simple-api:latest
    source: pull
    force_source: true

- name: Launch database container
  docker_container:
    name: my_database
    image: abdelrraoufsaidi/tp-devops-database
    recreate: true
    pull: yes
    env:
      #POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      #POSTGRES_DB: db
    networks:
      - name: my_app_network
    

# tasks file for roles/launch_database
